# Generated by Django 5.2.3 on 2026-06-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('excerpt', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.CharField(default='assets/img/services.jpg', max_length=255)),
                ('published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('degree', models.CharField(max_length=180)),
                ('school', models.CharField(max_length=180)),
                ('period', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(max_length=180)),
                ('company', models.CharField(max_length=180)),
                ('period', models.CharField(max_length=80)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(help_text='Use one responsibility per line for bullet points.')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('category', models.CharField(choices=[('app', 'App'), ('web', 'Web'), ('branding', 'Branding'), ('product', 'Product'), ('other', 'Other')], default='web', max_length=30)),
                ('short_description', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.CharField(default='assets/img/portfolio/app-1.jpg', max_length=255)),
                ('project_url', models.URLField(blank=True)),
                ('source_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('summary', models.TextField()),
                ('download_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'resume',
                'verbose_name_plural': 'resume',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('icon', models.CharField(default='bi bi-briefcase', max_length=60)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('title', models.CharField(default='Full Stack Developer', max_length=160)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField()),
                ('profile_image', models.CharField(default='assets/img/hero3.jpeg', help_text='Static path or full URL, for example assets/img/hero3.jpeg', max_length=255)),
                ('hero_image', models.CharField(default='assets/img/hero3.jpeg', max_length=255)),
                ('typed_roles', models.CharField(default='Developer, Designer, Freelancer', help_text='Comma-separated roles shown in the hero section.', max_length=255)),
                ('birthday', models.CharField(blank=True, max_length=60)),
                ('website', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('degree', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('freelance_status', models.CharField(default='Available', max_length=80)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('twitter', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('skype', models.CharField(blank=True, max_length=100)),
                ('linkedin', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'site profile',
                'verbose_name_plural': 'site profile',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('proficiency', models.PositiveSmallIntegerField(default=80)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
