# Generated by Django 5.2.3 on 2026-06-02 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myportifolio', '0003_siteprofile_whatsapp_seed_socials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteprofile',
            name='skype',
        ),
    ]
