# Generated by Django 5.2.3 on 2026-06-06 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportifolio', '0004_remove_siteprofile_skype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name': 'resume', 'verbose_name_plural': 'resumes'},
        ),
        migrations.AlterModelOptions(
            name='siteprofile',
            options={'verbose_name': 'site profile', 'verbose_name_plural': 'site profiles'},
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='tagline',
            field=models.TextField(blank=True),
        ),
    ]
