# Generated by Django 5.2.3 on 2026-06-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportifolio', '0004_remove_siteprofile_skype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='tagline',
            field=models.CharField(blank=True, max_length=1000000),
        ),
    ]
